version: '2.1'

services:

#  app:
#    image: 'docker-spring-boot-postgres:latest'
#    build: ./app/
#    container_name: app
#    ports:
#      - '8080:8080'
#    depends_on:
#      - db
#    volumes:
#      - ./app/pictures:/usr/src/app/pictures
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=compose-postgres
#      - SPRING_DATASOURCE_PASSWORD=compose-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
#      interval: 5s
#      timeout: 5s
#      retries: 2

  db:
    image: 'postgres:13.1-alpine'
    container_name: db_flats
    volumes:
      - ./docker:/backups
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

